### ISSUE TITLE
Use OSM instead of Google

### ISSUE THREAD

**Issue by nicolasmaia** [juancoob/Vegginner#1]
I thought it would be pretty sweet to have this distributed through [F-Droid](https://f-droid.org/), but I quickly noticed from the screenshot that it uses Google Maps instead of the libre OpenStreetMap. It'd be really great to have that instead, as it protects your users from Google and makes it possible for inclusion on F-Droid.

**Comment by juancoob** [comment]
Hi @picsi ,
I didn't think about it, but I don't have plans to port Google Maps to OpenStreetMap. However, thank you for your comments because I could change it if something goes wrong. I'll see how F-Droid could add Vegginner.
All the best,
juancoob
