### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by cvielet** [juancoob/Vegginner#2]
Would like to have any UI updates on some topics for the app?

**Comment by juancoob** [comment]
Hi, cvielet! what do you have in mind? I'm learning Kotlin and I want to rewrite the app. Thanks!

**Comment by cvielet** [comment]
okay, i am a designer and i found your concept of app really interesting, i just wanted to help during the hacktoberfest maybe with some design aspect, icons, ui/ux. etc if needed.

**Comment by juancoob** [comment]
Yes, thank you @cvielet !! What would you like to do? Could you recommend me any improvement for the app UI/UX?
